In [136]:
import numpy as np
import copy

In [137]:
sampl = np.random.uniform(low = 1, high=7, size=(100,))

In [138]:
sampl

array([3.15748711, 3.57165914, 3.73616487, 2.89402648, 5.02811818,
       2.97077205, 5.65958689, 4.90569999, 3.52445072, 4.57765295,
       2.50360208, 3.60614924, 6.08104625, 4.6236511 , 2.21724347,
       4.97979185, 6.86485475, 1.01828089, 4.62502214, 2.33027285,
       2.62997894, 6.29521568, 2.21445438, 6.15203331, 4.81823731,
       2.90701411, 3.20420327, 3.71533434, 4.56131367, 3.86375898,
       2.65359429, 4.88893377, 4.01428341, 6.98839943, 2.39918633,
       1.20332895, 3.19563049, 3.48025167, 4.82306593, 2.69558677,
       6.85213903, 6.29280724, 6.19981692, 1.78988809, 4.57168056,
       1.65021743, 2.977781  , 1.83925123, 6.67869511, 3.19052053,
       2.76949793, 3.05279258, 4.1564321 , 2.73229572, 3.13517385,
       3.00361208, 2.22861507, 4.8291556 , 5.69297174, 4.93785439,
       3.51056163, 3.09444437, 2.49522991, 2.56883877, 2.57618044,
       4.37751699, 6.30871415, 4.16627509, 1.12354846, 3.18682035,
       5.90686538, 2.01663676, 2.04104529, 4.47361944, 2.92291

In [139]:
sampl = np.sort(sampl)

In [140]:
sampl

array([1.01828089, 1.12354846, 1.20332895, 1.65021743, 1.78988809,
       1.83925123, 1.91598479, 1.93931062, 2.01663676, 2.04104529,
       2.21445438, 2.21724347, 2.22861507, 2.33027285, 2.39918633,
       2.49522991, 2.50360208, 2.51967287, 2.56234998, 2.56883877,
       2.57618044, 2.62997894, 2.65359429, 2.69558677, 2.73229572,
       2.76949793, 2.89402648, 2.90701411, 2.92291242, 2.97077205,
       2.977781  , 3.00361208, 3.02506582, 3.04789953, 3.05279258,
       3.09444437, 3.10066608, 3.13517385, 3.15748711, 3.18682035,
       3.19052053, 3.19563049, 3.20420327, 3.48025167, 3.51056163,
       3.52445072, 3.57066927, 3.57165914, 3.60614924, 3.71179441,
       3.71533434, 3.73616487, 3.86375898, 3.90937884, 4.01428341,
       4.1564321 , 4.16627509, 4.17012227, 4.31283554, 4.37751699,
       4.47361944, 4.56131367, 4.57168056, 4.57765295, 4.62166568,
       4.6236511 , 4.62502214, 4.81823731, 4.82306593, 4.8291556 ,
       4.87888437, 4.88893377, 4.90569999, 4.93785439, 4.97979

x1 = sampl

In [141]:
x1 = copy.deepcopy(sampl)

In [142]:
x1

array([1.01828089, 1.12354846, 1.20332895, 1.65021743, 1.78988809,
       1.83925123, 1.91598479, 1.93931062, 2.01663676, 2.04104529,
       2.21445438, 2.21724347, 2.22861507, 2.33027285, 2.39918633,
       2.49522991, 2.50360208, 2.51967287, 2.56234998, 2.56883877,
       2.57618044, 2.62997894, 2.65359429, 2.69558677, 2.73229572,
       2.76949793, 2.89402648, 2.90701411, 2.92291242, 2.97077205,
       2.977781  , 3.00361208, 3.02506582, 3.04789953, 3.05279258,
       3.09444437, 3.10066608, 3.13517385, 3.15748711, 3.18682035,
       3.19052053, 3.19563049, 3.20420327, 3.48025167, 3.51056163,
       3.52445072, 3.57066927, 3.57165914, 3.60614924, 3.71179441,
       3.71533434, 3.73616487, 3.86375898, 3.90937884, 4.01428341,
       4.1564321 , 4.16627509, 4.17012227, 4.31283554, 4.37751699,
       4.47361944, 4.56131367, 4.57168056, 4.57765295, 4.62166568,
       4.6236511 , 4.62502214, 4.81823731, 4.82306593, 4.8291556 ,
       4.87888437, 4.88893377, 4.90569999, 4.93785439, 4.97979

In [143]:
y1 = np.sort(np.random.uniform(low = 10, high = 4, size=(100,)))[::-1]

In [144]:
y1

array([9.89264836, 9.85035188, 9.78845267, 9.71837309, 9.43218704,
       9.43166794, 9.31861853, 9.26067851, 9.07337782, 9.0596235 ,
       9.05044251, 8.93327938, 8.92487424, 8.85875227, 8.78897836,
       8.78176845, 8.73291733, 8.64952964, 8.50166009, 8.47607106,
       8.44238094, 8.32695099, 8.20783825, 8.11659563, 8.09559764,
       7.9400728 , 7.87915374, 7.77477025, 7.75370596, 7.72258749,
       7.68181999, 7.54223118, 7.52780342, 7.43370737, 7.41881195,
       7.38703506, 7.34289393, 7.30705411, 7.28219123, 7.22853056,
       7.09689488, 6.93004352, 6.9037958 , 6.89727502, 6.82893857,
       6.8094751 , 6.78206644, 6.74472353, 6.70221739, 6.69973083,
       6.66698647, 6.63567441, 6.63475438, 6.58883465, 6.57683872,
       6.55117068, 6.46077833, 6.43624611, 6.38245884, 6.38127376,
       6.36794243, 6.34543269, 6.31820088, 6.20830717, 6.11448338,
       5.93001205, 5.85077125, 5.82950977, 5.73291234, 5.72400806,
       5.65990132, 5.59325835, 5.57449447, 5.39620747, 5.31684

In [145]:
x2 = np.sort(np.random.uniform(low = 10, high = 14, size=(100,)))

In [146]:
x2

array([10.01488235, 10.12616024, 10.14151917, 10.28344019, 10.29747098,
       10.31948565, 10.34755212, 10.37024607, 10.37929763, 10.40517293,
       10.42009501, 10.47088764, 10.50932626, 10.52731788, 10.54106617,
       10.56975951, 10.61600485, 10.6319479 , 10.7243057 , 10.74912268,
       10.82417246, 10.83320978, 10.86631903, 10.93480971, 10.93795335,
       10.96148321, 10.96888025, 11.00263824, 11.04444932, 11.16251939,
       11.21691565, 11.26309642, 11.31541386, 11.33438573, 11.44412226,
       11.48811913, 11.54029351, 11.6084805 , 11.62611577, 11.66492605,
       11.69692429, 11.75207844, 11.88405441, 11.94719787, 12.01970669,
       12.1476204 , 12.15866627, 12.26638051, 12.31542365, 12.32185756,
       12.32427772, 12.35925279, 12.40128644, 12.41985151, 12.45945659,
       12.51658928, 12.5447377 , 12.58306463, 12.59364233, 12.61239534,
       12.62704684, 12.67499094, 12.72262397, 12.72338029, 12.73184694,
       12.75788561, 12.76852854, 12.80890749, 12.84408497, 12.97

In [147]:
y2 = np.sort(np.random.uniform(low = 5, high = 21, size=(100,)))

In [148]:
x3 = np.sort(np.random.uniform(low = 14, high = 19, size=(100,)))

In [162]:
y3 = np.sort(np.random.uniform(low = 5, high = 17, size=(100,)))

In [163]:
y4 = np.sort(np.random.uniform(low = 8, high = 1, size=(100,)))[::-1]

In [164]:
x4 = np.sort(np.random.uniform(low = 19, high = 21, size=(100,)))

In [165]:
y4

array([7.92188028, 7.86017159, 7.85762204, 7.83191439, 7.83014096,
       7.72943233, 7.68575815, 7.55905943, 7.5209419 , 7.44256779,
       7.37738575, 7.2557296 , 7.21515439, 7.20535054, 7.16504379,
       7.15095371, 6.87815093, 6.86296663, 6.69823163, 6.56819159,
       6.44227775, 6.42519933, 6.40771704, 6.35717393, 6.30423773,
       6.29049983, 6.24399533, 6.21204758, 6.08676585, 6.04090086,
       6.01238018, 5.97730685, 5.90689492, 5.71673254, 5.68308722,
       5.65261582, 5.63776443, 5.61524817, 5.61083391, 5.47608013,
       5.35563254, 5.28169147, 5.24320506, 5.21826184, 5.05469726,
       4.80040445, 4.73130411, 4.60498437, 4.60406591, 4.54207342,
       4.5384543 , 4.51740462, 4.33839198, 4.20742603, 4.13333408,
       4.12028483, 4.10144548, 4.09699223, 4.03855211, 3.99373487,
       3.91036771, 3.86140176, 3.74074983, 3.72436235, 3.50807344,
       3.45705701, 3.37519223, 3.32282292, 3.32066804, 3.09794097,
       3.02145896, 2.99630594, 2.8907439 , 2.68418389, 2.65645

In [166]:
del x
x = np.concatenate((x1, x2))
x.shape

(200,)

In [167]:
x = np.concatenate((x, x3))
x = np.concatenate((x, x4))
print(x3.shape)
print(x4.shape)
print(x.shape)
x

(100,)
(100,)
(400,)


array([ 1.01828089,  1.12354846,  1.20332895,  1.65021743,  1.78988809,
        1.83925123,  1.91598479,  1.93931062,  2.01663676,  2.04104529,
        2.21445438,  2.21724347,  2.22861507,  2.33027285,  2.39918633,
        2.49522991,  2.50360208,  2.51967287,  2.56234998,  2.56883877,
        2.57618044,  2.62997894,  2.65359429,  2.69558677,  2.73229572,
        2.76949793,  2.89402648,  2.90701411,  2.92291242,  2.97077205,
        2.977781  ,  3.00361208,  3.02506582,  3.04789953,  3.05279258,
        3.09444437,  3.10066608,  3.13517385,  3.15748711,  3.18682035,
        3.19052053,  3.19563049,  3.20420327,  3.48025167,  3.51056163,
        3.52445072,  3.57066927,  3.57165914,  3.60614924,  3.71179441,
        3.71533434,  3.73616487,  3.86375898,  3.90937884,  4.01428341,
        4.1564321 ,  4.16627509,  4.17012227,  4.31283554,  4.37751699,
        4.47361944,  4.56131367,  4.57168056,  4.57765295,  4.62166568,
        4.6236511 ,  4.62502214,  4.81823731,  4.82306593,  4.82

In [168]:
del y
y = np.concatenate((y1, y2))

In [169]:
y = np.concatenate((y, y3))
y = np.concatenate((y, y4))
print(y)
print(y.shape)

[ 9.89264836  9.85035188  9.78845267  9.71837309  9.43218704  9.43166794
  9.31861853  9.26067851  9.07337782  9.0596235   9.05044251  8.93327938
  8.92487424  8.85875227  8.78897836  8.78176845  8.73291733  8.64952964
  8.50166009  8.47607106  8.44238094  8.32695099  8.20783825  8.11659563
  8.09559764  7.9400728   7.87915374  7.77477025  7.75370596  7.72258749
  7.68181999  7.54223118  7.52780342  7.43370737  7.41881195  7.38703506
  7.34289393  7.30705411  7.28219123  7.22853056  7.09689488  6.93004352
  6.9037958   6.89727502  6.82893857  6.8094751   6.78206644  6.74472353
  6.70221739  6.69973083  6.66698647  6.63567441  6.63475438  6.58883465
  6.57683872  6.55117068  6.46077833  6.43624611  6.38245884  6.38127376
  6.36794243  6.34543269  6.31820088  6.20830717  6.11448338  5.93001205
  5.85077125  5.82950977  5.73291234  5.72400806  5.65990132  5.59325835
  5.57449447  5.39620747  5.31684498  5.22787721  5.1453306   5.11627054
  5.04655036  5.03549022  4.97708024  4.91596015  4

In [170]:
for i in range(400):
    print(x[i], "  ", y[i])

1.0182808913404466    9.892648362691238
1.1235484610760578    9.85035187840257
1.2033289480526659    9.788452668211896
1.650217433815826    9.718373093334069
1.7898880876281813    9.43218704129
1.8392512333027558    9.431667937567598
1.915984792891502    9.318618528677245
1.939310622410545    9.260678513246964
2.0166367640116962    9.073377815746266
2.0410452918668183    9.05962350166145
2.2144543848228917    9.050442514806042
2.2172434709558253    8.9332793771684
2.2286150726913228    8.924874241567714
2.3302728489508797    8.858752274667472
2.399186330992861    8.788978364197774
2.4952299092848795    8.781768452032752
2.503602081080301    8.732917326715198
2.519672867611667    8.649529637506852
2.562349982219512    8.501660089550553
2.568838767054439    8.476071058461372
2.576180436077238    8.442380938594534
2.629978943989478    8.326950988936636
2.6535942891025295    8.207838249999748
2.6955867668679923    8.11659563474582
2.732295720183588    8.095597641947435
2.7694979336963303  

In [171]:
for i in range(400):
    print("(",x[i],",",y[i],")")

( 1.0182808913404466 , 9.892648362691238 )
( 1.1235484610760578 , 9.85035187840257 )
( 1.2033289480526659 , 9.788452668211896 )
( 1.650217433815826 , 9.718373093334069 )
( 1.7898880876281813 , 9.43218704129 )
( 1.8392512333027558 , 9.431667937567598 )
( 1.915984792891502 , 9.318618528677245 )
( 1.939310622410545 , 9.260678513246964 )
( 2.0166367640116962 , 9.073377815746266 )
( 2.0410452918668183 , 9.05962350166145 )
( 2.2144543848228917 , 9.050442514806042 )
( 2.2172434709558253 , 8.9332793771684 )
( 2.2286150726913228 , 8.924874241567714 )
( 2.3302728489508797 , 8.858752274667472 )
( 2.399186330992861 , 8.788978364197774 )
( 2.4952299092848795 , 8.781768452032752 )
( 2.503602081080301 , 8.732917326715198 )
( 2.519672867611667 , 8.649529637506852 )
( 2.562349982219512 , 8.501660089550553 )
( 2.568838767054439 , 8.476071058461372 )
( 2.576180436077238 , 8.442380938594534 )
( 2.629978943989478 , 8.326950988936636 )
( 2.6535942891025295 , 8.207838249999748 )
( 2.6955867668679923 , 8.1165

( 19.27382683789603 , 6.878150931501285 )
( 19.307428628755908 , 6.862966630209195 )
( 19.32634301756772 , 6.698231625865818 )
( 19.345731083291415 , 6.5681915924600585 )
( 19.351317788381703 , 6.44227774525363 )
( 19.366916696486797 , 6.425199333440495 )
( 19.393947143988143 , 6.407717038667124 )
( 19.402064711792946 , 6.357173931957616 )
( 19.478576955914395 , 6.304237731631917 )
( 19.511918322078397 , 6.290499828787392 )
( 19.532126264608657 , 6.243995326730966 )
( 19.535146593962214 , 6.21204758115903 )
( 19.540986459447602 , 6.086765845673051 )
( 19.59045099792397 , 6.040900857813031 )
( 19.626666192390104 , 6.012380183291844 )
( 19.634055966396595 , 5.977306850859611 )
( 19.66049241419831 , 5.906894916592953 )
( 19.66373273668538 , 5.7167325449531745 )
( 19.668476582646374 , 5.6830872208712275 )
( 19.72237744575784 , 5.652615818336086 )
( 19.762897373718324 , 5.637764432612884 )
( 19.792878216719 , 5.615248169646508 )
( 19.79941420527427 , 5.610833910569607 )
( 19.804452401198986